version: "2"
services:
  mongodb:
    image: mongo:2.6
    command: mongod --setParameter textSearchEnabled=true
    ports:
      - 27017:27017
    volumes:
      - /Users/twan/data/db:/data/db

  scribe:
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    ports:
      - 80:80
    environment:
      - DEVISE_SECRET_TOKEN
      - SECRET_KEY_BASE_TOKEN
      - GOOGLE_ID
      - GOOGLE_SECRET
    volumes:
      - /Users/twan/scribeAPI/project:/src/project
      - /Users/twan/scribeAPI/lib:/src/lib
      - /Users/twan/scribeAPI/app:/src/app
      - /Users/twan/scribeAPI/config:/src/config
